apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app:  webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app:  queue
  replicas: 1
  template:
    metadata:
      labels:
        app:  queue
    spec: 
      containers:   
        - name: queue
          image: richardchesterwood/k8s-fleetman-queue:release1
          ports:
          - containerPort: 8161
